# Move the directory to the second line
# format="$all$directory$character"

# format="""
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $character"""

command_timeout = 1000
# Disable the blank line between shell prompts
add_newline = false

[line_break]
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Show command duration over 2,000 milliseconds (= 2 sec)
[cmd_duration]
format = "took [$duration]($style) "
min_time = 2_000

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

